swagger: "2.0"
info:
  version: 1.0.0
  title: shopinglist
  description: Shping list API
  termsOfService: http://swagger.io/terms/
  contact:
    name: Swagger API Team
    email: foo@example.com
    url: http://madskristensen.net
  license:
    name: MIT
    url: http://github.com/gruntjs/grunt/blob/master/LICENSE-MIT
host: petstore.swagger.io
basePath: /api
schemes:
  - http
consumes:
  - application/json
produces:
  - application/json
paths:
  /shopinglists:
    get:
      description: |
        Retuns a list of stored shoping lists.  Each entry has a short description and a last modified date.
      operationId: findLists
      parameters:
        - name: tags
          in: query
          description: tags to filter by
          required: false
          type: array
          collectionFormat: csv
          items:
            type: string
        - name: limit
          in: query
          description: maximum number of results to return
          required: false
          type: integer
          format: int32
      responses:
        200:
          description: lists response
          schema:
            type: array
            items:
              $ref: '#/definitions/List'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    post:
      description: Creates a new shopinglist.  Duplicates are allowed.
      operationId: createList
      parameters:
        - name: list
          in: body
          description: List to add
          required: true
          schema:
            $ref: '#/definitions/NewList'
      responses:
        200:
          description: List response
          schema:
            $ref: '#/definitions/List'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
  /shopinglists/{id}:
    get:
      description: Returns a shoping list based on a single ID.
      operationId: find list by id
      parameters:
        - name: id
          in: path
          description: ID of the list to fetch
          required: true
          type: integer
          format: int64
      responses:
        200:
          description: list response
          schema:
            $ref: '#/definitions/List'
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
    delete:
      description: deletes a single list based on the ID supplied
      operationId: deleteList
      parameters:
        - name: id
          in: path
          description: ID of the list to delete
          required: true
          type: integer
          format: int64
      responses:
        204:
          description: list deleted
        default:
          description: unexpected error
          schema:
            $ref: '#/definitions/Error'
definitions:
  List:
    allOf:
      - $ref: '#/definitions/NewList'
      - required:
        - id
        properties:
          id:
            type: integer
            format: int64
  NewList:
    required:
      - name
    properties:
      name:
        type: string
      tag:
        type: string
  Error:
    required:
      - code
      - message
    properties:
      code:
        type: integer
        format: int32
      message:
        type: string